#!/usr/bin/env python
"""Rebuild all manuscript numerical assets from the explicitly pinned audited run.

Run from PAPER: python scripts/generate_assets.py
No input, raw data, original output or replication code is modified.
"""
from __future__ import annotations
from pathlib import Path
from copy import deepcopy
from datetime import datetime, timezone
import argparse, hashlib, json, platform, sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from paper_config import (PRIMARY_VERSION, PRIMARY_FOLDER, PRIMARY_MAPPING,
                          PRIMARY_H0, SECTORAL_VERSION, FULL_VERSION, FULL_FOLDER)

PAPER = Path(__file__).resolve().parents[1]
REPLICATION = (PAPER.parent / "replication_package" if (PAPER.parent / "replication_package" / "run_all.py").is_file() else PAPER.parent)
RUN_ID = "20260905_005724_846373"
MODES = ["bilateral", "flat_below"]
MODE_LABEL = {"bilateral": "Bilateral", "flat_below": "Só acima do pico"}
MODE_SHORT = {"bilateral": "Bilateral", "flat_below": "Acima do pico"}
COLORS = {"bilateral": "#174F78", "flat_below": "#B26328"}
SOURCES = {}

def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()

def read(path, kind="json"):
    path = Path(path)
    SOURCES[str(path.relative_to(PAPER.parent))] = sha(path)
    return json.loads(path.read_text(encoding="utf-8-sig")) if kind == "json" else pd.read_csv(path)

def dump(path, value):
    Path(path).write_text(json.dumps(value, indent=2, ensure_ascii=False), encoding="utf-8")

def fmt(value, digits=2, signed=False):
    if pd.isna(value): return "--"
    if abs(float(value)) < .5 * 10**(-digits): value = 0.
    return (f"{value:+.{digits}f}" if signed else f"{value:.{digits}f}").replace(".", ",")

def series(axis):
    axis.spines[["right", "top"]].set_visible(False)
    axis.grid(axis="y", alpha=.18, linewidth=.6)
    axis.set_axisbelow(True)
    axis.yaxis.set_major_formatter(FuncFormatter(lambda x, pos: fmt(x, 1)))

def savefig(fig, out, name):
    # Preserve the plots and numerical series, applying the journal font.
    from matplotlib.text import Text
    for item in fig.findobj(match=Text):
        item.set_fontfamily("Times New Roman")
        if item.get_fontweight() in ("bold", "heavy", 700, 800):
            item.set_fontweight("normal")
            item.set_fontstyle("italic")
    for ext in ("pdf", "png"):
        fig.savefig(out / f"{name}.{ext}", dpi=190, bbox_inches="tight",
                    metadata={"Creator": "PAPER/scripts/generate_assets.py"})
    plt.close(fig)

def table(out, filename, label, caption, headers, rows, note, aligns=None):
    n = len(headers)
    lines = [r"% Generated by scripts/generate_assets.py; do not edit.",
             r"\begin{table}[!htbp]", r"\centering", r"\normalsize",
             r"\caption{" + caption + r"}\label{" + label + "}",
             r"\setlength{\tabcolsep}{4pt}",
             r"\begin{tabular}{" + (aligns or "l" + "r"*(n-1)) + "}",
             r"\toprule", " & ".join(headers) + r" \\", r"\midrule"]
    for row in rows:
        if isinstance(row, str):
            lines += [r"\addlinespace", r"\multicolumn{" + str(n) + r"}{l}{\textit{" + row + r"}} \\", r"\addlinespace"]
        else: lines.append(" & ".join(map(str, row)) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\par\smallskip",
              r"\begin{minipage}{0.98\linewidth}\normalsize " + note + r"\end{minipage}",
              r"\end{table}", ""]
    (out / filename).write_text("\n".join(lines), encoding="utf-8")

def check_run(run):
    manifest = read(run / "RUN_MANIFEST.json")
    if manifest["status"] != "complete":
        raise ValueError("Refusing an incomplete run")
    # Fail if archived results or the shared code changed after their audited run.
    checked = 0
    for relative, expected in manifest["output_hashes"].items():
        path = run / relative.replace("\\", "/")
        if not path.is_file() or sha(path) != expected:
            raise ValueError(f"Archived output differs from run manifest: {relative}")
        checked += 1
    for relative, expected in manifest["code_hashes"].items():
        path = REPLICATION / relative.replace("\\", "/")
        if not path.is_file() or sha(path) != expected:
            raise ValueError(f"Model code differs from audited run: {relative}")
    return checked

def curves(run, out, national):
    sys.path.insert(0, str(REPLICATION))
    from src.model.simulation import run_simulation
    from src.calibration.corrected_pipeline import result_row
    rows = []
    anchor_errors = []
    for folder, mapping, version in [
        ("national_empirical", "habitual_integral", "reprocessed_data"),
        ("national_empirical_topcode44", "habitual_limitada44", "reprocessed_topcoded44")]:
        inputs = read(run / folder / "INPUTS.json")
        bridges = read(run / folder / "BRIDGE.json")
        for bridge in bridges:
            mode = bridge["efficiency_mode"]
            for cap in np.arange(30, 44.001, .25):
                targets = deepcopy(inputs["targets"])
                targets["H1"]["value"] = float(cap)
                sim = run_simulation(targets, sigma_sub=bridge["sigma_sub"], omega=bridge["omega"],
                    theta=inputs["theta"], group_specs=inputs["group_specs"], efficiency_mode=mode,
                    hours_bins=inputs["hours_bins"], share_basis=inputs["share_basis"],
                    resource_costs=inputs["resource_costs"])
                row = result_row(sim, version, float(cap), mode, mapping=mapping)
                row["baseline_operator_h0"] = targets["H0"]["value"]
                row["restoration_residual"] = sim["A_req_details"]["relative_error"]
                rows.append(row)
                if cap in (36, 40):
                    old = national.query("version == @version and efficiency_mode == @mode and hours_cap == @cap").iloc[0]
                    for key in ["dY_pct","A_req_pct","A_req_frozen_pct","dGHH_pct","CE_pct","informality_pct"]:
                        anchor_errors.append(abs(row[key] - old[key]))
    if max(anchor_errors) > 1.e-8:
        raise ValueError(f"Recomputed curves fail canonical anchors: {max(anchor_errors)}")
    df = pd.DataFrame(rows)
    reference = df.loc[df.version.eq(PRIMARY_VERSION) & df.hours_cap.eq(PRIMARY_H0)]
    identity_keys = ['dY_pct','A_req_pct','A_req_frozen_pct','dGHH_pct','CE_pct','dInf_pp']
    identity_errors = {key:float(reference[key].abs().max()) for key in identity_keys}
    if len(reference)!=2 or max(identity_errors.values())>1.e-9:
        raise ValueError(f'The 44h reference is not an identity: {identity_errors}')
    dump(out/'reference_44_checks.json',{'status':'passed','baseline_operator_h0':PRIMARY_H0,
        'version':PRIMARY_VERSION,'errors':identity_errors,
        'method':'Recomputed with identical baseline and counterfactual hours; no shift of plotted values'})
    df.to_csv(out/"curves_national.csv", index=False, encoding="utf-8-sig")
    return df, max(anchor_errors)

def make_national_tables(national, out):
    primary = national.loc[national.version.eq(PRIMARY_VERSION)].copy()
    primary.to_csv(out/"national_results.csv", index=False, encoding="utf-8-sig")
    national.loc[national.version.eq(FULL_VERSION)].to_csv(
        out/"national_results_integral.csv", index=False, encoding="utf-8-sig")
    rows = []
    # Metric rows keep all headline quantities legible at manuscript column width.
    cols = [primary.query("efficiency_mode == @m and hours_cap == @h").iloc[0] for m in MODES for h in [40,36]]
    for label, key in [
        (r"$\Delta Y$ (\%)", "dY_pct"),
        (r"$A_{\mathrm{req}}$ (\%)", "A_req_pct"),
        (r"$A_{\mathrm{req}}$, composição fixa (\%)", "A_req_frozen_pct"),
        (r"Informalidade após reforma (\%)", "informality_pct"),
        (r"$\Delta$ informalidade (p.p.)", "dInf_pp"),
        (r"$\Delta GHH$ (\%)", "dGHH_pct"),
        (r"$CE$ (\% de $C_0$)", "CE_pct")]:
        rows.append([label] + [fmt(r[key], 3) for r in cols])
    table(out, "tab_national.tex", "tab:mainresults",
          "Resultados nacionais da redução a partir de 44h, com ponte horária recalibrada",
          ["Indicador", r"\shortstack{Bilateral\\40h}", r"\shortstack{Bilateral\\36h}", r"\shortstack{Acima\\40h}", r"\shortstack{Acima\\36h}"], rows,
          r"Fonte: PNAD Contínua 2024T4 reprocessada e simulações. Acima: fadiga somente acima do pico. "
          r"Base: horas formais $\min\{h^{obs},44\}$, pesos PNAD preservados, horas informais inalteradas, "
          r"informalidade de 38,600\%, $\sigma=1{,}326$; "
          r"$\omega=0{,}675651$ (bilateral) e $0{,}676650$ (acima). A limitação inicial a 44h é uma hipótese de representação, "
          r"não uma observação de horas contratuais. $A_{\mathrm{req}}$ recompõe o produto dessa base com composição reotimizada em cada avaliação; "
          r"a variante fixa mantém a composição inicial. $\Delta Y$ usa $Y_0$, $\Delta GHH$ usa $GHH_0$ e $CE$ usa $C_0$ como denominador. "
          r"Capital e ocupação totais fixos; cunhas são transferências e ajuste consome recursos.")
    names = {
        "original": "Original",
        "code_corrected_frozen_inputs": "Código corrigido; entradas congeladas",
        "bridge_recalibrated_assumed_hourly": "Ponte horária legada recalibrada",
        "rais_verified_only": "Somente RAIS verificada",
        "single_group_frozen_control": "Controle de um grupo; entradas congeladas",
        "reprocessed_data_fixed_omega": r"PNAD reprocessada; $\omega$ fixo",
        "reprocessed_data": "PNAD integral; sensibilidade e ponte recalibrada",
        "reprocessed_topcoded44": "Principal: PNAD com base 44h e nova ponte"}
    rows = []
    for version in names:
        rows.append(names[version])
        for mode in MODES:
            for h in [40,36]:
                r = national.query("version == @version and efficiency_mode == @mode and hours_cap == @h").iloc[0]
                rows.append([f"{MODE_SHORT[mode]}, {h}h"] + [fmt(r[k], 2) for k in ["dY_pct","A_req_pct","informality_pct","dGHH_pct","CE_pct"]])
    # Two ordinary tables keep the transition audit readable and avoid a 40-row float.
    for index, selected in enumerate([list(names)[:4], list(names)[4:]], 1):
        selected_rows = []
        for version in selected:
            selected_rows.append(names[version])
            for mode in MODES:
                for h in [40,36]:
                    r = national.query("version == @version and efficiency_mode == @mode and hours_cap == @h").iloc[0]
                    selected_rows.append([f"{MODE_SHORT[mode]}, {h}h"] + [fmt(r[k],2) for k in ["dY_pct","A_req_pct","informality_pct","dGHH_pct","CE_pct"]])
        table(out, f"tab_comparison_part{index}.tex", "tab:comparison" if index==1 else "tab:comparison_data",
              "Comparação entre versões: " + ("código e hipóteses legadas" if index==1 else "agregação e dados reprocessados"),
              ["Função e teto", r"$\Delta Y$ (\%)", r"$A_{\rm req}$ (\%)", "Inf. (\\%)", r"$\Delta GHH$ (\%)", r"$CE$ (\%)"],
              selected_rows,
              r"Fonte: execução original arquivada e versões explicitadas da replicação corrigida. "
              r"$\sigma=1{,}326$ em todas as linhas. A versão original é uma nova execução do código preservado; seu $CE$ "
              r"foi calculado das alocações originais. Informalidade é nível após reforma. "
              r"As versões intermediárias isolam modificações condicionais e não são todas calibrações empíricas preferidas. "
              r"Na versão com RAIS, vínculos por estabelecimento são combinados apenas experimentalmente com taxas de informalidade legadas. "
              r"Os conceitos e denominadores seguem a Tabela~\ref{main-tab:mainresults} do artigo.")
    (out/"tab_comparison.tex").write_text("\\input{generated/tab_comparison_part1}\n\\input{generated/tab_comparison_part2}\n", encoding="utf-8")
    national.to_csv(out/"comparison_results.csv", index=False, encoding="utf-8-sig")
    return primary

def make_curve_figures(df, out):
    from original_main_figures import plot_areq, plot_welfare
    savefig(plot_areq(df), out, "fig_areq_vs_hours_pt")
    savefig(plot_welfare(df), out, "fig_welfare_schedule_pt")


def make_sensitivity(national, sensitivity, out):
    sensitivity.to_csv(out/"sensitivity_empirical.csv",index=False,encoding="utf-8-sig")
    fig, axes=plt.subplots(1,2,figsize=(10,4.0),sharey=True)
    cases=[("Principal: base 44h",PRIMARY_VERSION,None),("PNAD integral",FULL_VERSION,None),
           ("Sem fadiga\n(base 44h)",None,1.0)]
    base=np.arange(len(cases))
    for ax,h in zip(axes,[40,36]):
        for j,mode in enumerate(MODES):
            values=[]
            for label,version,eq in cases:
                r=(national.query("version == @version and efficiency_mode == @mode and hours_cap == @h").iloc[0]
                   if version else sensitivity.query("dimension == 'efficiency' and E_Q == @eq and efficiency_mode == @mode and hours_cap == @h").iloc[0])
                values.append(r.A_req_pct)
            ax.bar(base+(j-.5)*.32,values,width=.30,color=COLORS[mode],label=MODE_LABEL[mode])
            for x,v in zip(base+(j-.5)*.32,values):
                ax.text(x,v+.14,fmt(v,2),ha="center",va="bottom",fontsize=8.5)
        ax.set(title=f"Teto habitual de {h}h",xticks=base,xticklabels=[c[0] for c in cases],ylim=(0,11.1))
        ax.tick_params(axis="x",labelsize=9)
        series(ax)
    axes[0].set_ylabel(r"$A_{\mathrm{req}}$ (%)")
    axes[1].legend(frameon=False,fontsize=8.5,loc="upper left")
    fig.tight_layout(w_pad=2)
    savefig(fig,out,"fig_sensitivity_pt")
    rows=[]
    for dim, param, symbol in [("efficiency","E_Q",r"$E_Q$"),("peak","h_star",r"$h^\star$"),
                               ("eta","eta_I",r"$\eta_I$"),("sigma","sigma_sub",r"$\sigma$")]:
        vals=sorted(sensitivity.query("dimension == @dim")[param].unique())
        formatted=[fmt(v, 3 if param=="sigma_sub" else (2 if param=="eta_I" else 1)) for v in vals]
        valtext="; ".join(formatted)
        if len(formatted)>3:
            valtext=r"\shortstack[l]{"+"; ".join(formatted[:2])+r"\\"+"; ".join(formatted[2:])+"}"
        values=[]
        for mode in MODES:
            for h in [40,36]:
                ss=sensitivity.query("dimension == @dim and efficiency_mode == @mode and hours_cap == @h")
                values.append(f"{fmt(ss.A_req_pct.min())} a {fmt(ss.A_req_pct.max())}")
        rows.append([symbol, valtext]+values)
    table(out,"tab_sensitivity.tex","tab:sensitivity","Sensibilidades condicionais com a ponte horária recalibrada",
          ["Parâmetro","Valores avaliados","Bil. 40h","Bil. 36h","Acima 40h","Acima 36h"],rows,
          r"Fonte: 64 simulações com PNAD 2024T4 e base formal limitada a 44h. As quatro últimas colunas mostram o mínimo e o máximo de $A_{\rm req}$ (\%) "
          r"entre os valores listados; os pontos individuais estão em \texttt{generated/sensitivity\_empirical.csv}. "
          r"Cada dimensão varia separadamente, incluindo pontos interiores; as demais hipóteses permanecem na base. "
          r"A cada ponto, $\omega$ e as cunhas são recalibrados ao mesmo prêmio horário e à informalidade inicial. "
          r"$E_Q=1$ implica ausência de fadiga. Trata-se de uma grade de sensibilidade, sem interpretação de conjunto identificado.",
          aligns="llrrrr")
    rows=[]
    for label,version,eq in cases:
        for mode in MODES:
            rr=[]
            for h in [40,36]:
                r=(national.query("version == @version and efficiency_mode == @mode and hours_cap == @h").iloc[0]
                   if version else sensitivity.query("dimension == 'efficiency' and E_Q == @eq and efficiency_mode == @mode and hours_cap == @h").iloc[0])
                rr.extend([fmt(r.A_req_pct),fmt(r.CE_pct)])
            rows.append([label.replace("\n"," "),MODE_SHORT[mode]]+rr)
    table(out,"tab_mapping.tex","tab:mapping","Horas de base e fadiga: compensação e equivalente de consumo",
          ["Cenário","Função",r"$A_{\rm req}^{40}$",r"$CE^{40}$",r"$A_{\rm req}^{36}$",r"$CE^{36}$"],rows,
          r"Valores em \%. A limitação inicial a 44h é uma hipótese adicional de mensuração/cumprimento; altera também o "
          r"denominador da ponte de remuneração horária, que é recalibrada. A base integral preserva todas as horas observadas. "
          r"A ausência de fadiga mantém a base limitada a 44h e usa $E_Q=1$, $\kappa=0$. "
          r"Essas alternativas não são observações distintas de horas contratuais.",
          aligns="llrrrr")

def make_sectoral(sectors,out):
    d=sectors.loc[sectors.scenario_variant.eq(SECTORAL_VERSION)].copy()
    d.to_csv(out/"sectoral_results.csv",index=False,encoding="utf-8-sig")
    names={"agriculture":"Agropecuária","industry":"Indústria e construção","services":"Serviços","AGGREGATE":"Agregado"}
    keys=[s for s in names if s in d.sector.unique()]
    # Aggregate key used by current engine is normalized below if necessary.
    if len(keys)!=4: raise ValueError(f"Unexpected sector names: {d.sector.unique()}")
    rows=[]
    for mode in MODES:
        for h in [40,36]:
            rows.append(f"{MODE_LABEL[mode]}, teto de {h}h")
            for s in keys:
                r=d.query("efficiency_mode == @mode and h1 == @h and sector == @s").iloc[0]
                rows.append([names[s]]+[fmt(r[k],2) for k in ["dY_pct","A_req_pct","A_req_frozen_pct","dInf_pp","dGHH_pct","CE_pct"]])
    table(out,"tab_sectoral.tex","tab:sectoral_results","Resultados setoriais com momentos da PNAD 2024T4",
          ["Setor",r"$\Delta Y$",r"$A_{\rm req}$",r"$A_{\rm req}^{fixo}$",r"$\Delta$ Inf.",r"$\Delta GHH$",r"$CE$"],rows,
          r"Fonte: PNAD 2024T4 reprocessada; todas as colunas em \%, exceto informalidade em pontos percentuais. "
          r"Base formal limitada a 44h; horas informais preservadas. O capital setorial e os parâmetros tecnológicos são hipóteses; $\sigma=1{,}326$. "
          r"A ponte soma folhas e horas entre os três setores classificados, com horas formais limitadas a 44h e "
          r"$\omega=" + fmt(d.loc[d.efficiency_mode.eq('bilateral'),'omega'].iloc[0],6) + r"$ (bilateral) e $" +
          fmt(d.loc[d.efficiency_mode.eq('flat_below'),'omega'].iloc[0],6) + r"$ (acima). "
          r"O agregado recompõe a soma dos produtos com multiplicador comum de produtividade; não é a média dos $A_{\rm req}$ setoriais. "
          r"Os 0,019\% de ocupados sem atividade classificável são excluídos e as participações são renormalizadas. "
          r"Capital e ocupação setoriais são fixos; os resultados não incorporam relações insumo-produto.")
    from original_appendix_figures import plot_sectoral_areq
    savefig(plot_sectoral_areq(d), out, "fig_sectoral_areq")


def make_decomposition(primary,out,details):
    level_rows=[]
    level_records=[]
    for mode in MODES:
        for h in [40,36]:
            decomposition=details[f"{mode}_{h}"]["decomposition"]
            levels=decomposition["levels"]
            ordered=[levels[k] for k in ["baseline","physical_hours","efficiency","reallocation"]]
            reconstructed=100.*(ordered[-1]-ordered[0])/ordered[0]
            if abs(reconstructed-decomposition["total_pct"])>1.e-10:
                raise ValueError("Intermediate decomposition levels do not reproduce output change")
            level_records.append(dict(efficiency_mode=mode,hours_cap=h,
                Y0=ordered[0],YH=ordered[1],YE=ordered[2],Y1=ordered[3],
                denominator="Y0",order="physical_hours;efficiency;formal_informal_reallocation"))
            level_rows.append([MODE_SHORT[mode],f"{h}h"]+[fmt(value,6) for value in ordered])
    pd.DataFrame(level_records).to_csv(out/"decomposition_levels.csv",index=False,encoding="utf-8-sig")
    table(out,"tab_decomposition_levels.tex","tab:decomposition_levels",
          "Níveis intermediários do produto na decomposição nacional",
          ["Função","Teto",r"$Y_0$",r"$Y_H$",r"$Y_E$",r"$Y_1$"],level_rows,
          r"Fonte: simulações nacionais com PNAD 2024T4, base formal limitada a 44h e ponte horária recalibrada. "
          r"Produto em unidades normalizadas do modelo, com seis casas decimais; não em reais. "
          r"A ordem é horas físicas, eficiência e realocação formal--informal: $Y_H$ altera somente as horas, "
          r"$Y_E$ atualiza também a eficiência, mantendo a composição inicial, e $Y_1$ permite a reotimização. "
          r"As contribuições percentuais são $100(Y_H-Y_0)/Y_0$, $100(Y_E-Y_H)/Y_0$ e "
          r"$100(Y_1-Y_E)/Y_0$, cuja soma é $100(Y_1-Y_0)/Y_0$. "
          r"Os cálculos e o CSV usam precisão integral; diferenças aparentes após arredondamento não são resíduos econômicos.",
          aligns="llrrrr")
    records=[]
    for h in [40,36]:
        for mode in MODES:
            r=primary.query("efficiency_mode == @mode and hours_cap == @h").iloc[0]
            record={"mode":mode,"cap":h,
                    **{key:float(r[key]) for key in ["hours_pct","efficiency_pct","reallocation_pct"]},
                    "total_pct":float(r.dY_pct)}
            if abs(sum(record[key] for key in ["hours_pct","efficiency_pct","reallocation_pct"])-record["total_pct"])>1e-9:
                raise ValueError("Decomposition contributions do not sum to the total")
            records.append(record)
    from original_appendix_figures import plot_decomposition
    savefig(plot_decomposition(primary),out,"fig_decomposition")
    pd.DataFrame(records).to_csv(out/"decomposition.csv",index=False,encoding="utf-8-sig")


def make_tfp(primary, out):
    path=REPLICATION/"data_raw/fred/RTFPNABRA632NRUG_pwt110.csv"
    d=read(path,"csv").rename(columns={"RTFPNABRA632NRUG":"rtfpna"})
    d["year"]=pd.to_datetime(d["observation_date"]).dt.year
    if d.year.max()!=2023 or abs(float(d.query("year == 2021").rtfpna.iloc[0])-1)>1e-8:
        raise ValueError("Unexpected PWT vintage")
    values=d.set_index("year").rtfpna
    def growth(a,b):return 100*((values[b]/values[a])**(1/(b-a))-1)
    periods=[(1990,2023),(1990,2019),(2000,2010),(2010,2023)]
    rolling=[(a,a+10,growth(a,a+10)) for a in range(1990,2010)]
    best=max(rolling,key=lambda x:x[2])
    hist=[{"start":a,"end":b,"growth_pct_year":growth(a,b)} for a,b in periods]
    pd.DataFrame(hist).to_csv(out/"tfp_history_rates.csv",index=False,encoding="utf-8-sig")
    d.to_csv(out/"tfp_history.csv",index=False,encoding="utf-8-sig")
    rows=[];table_rows=[]
    for mode in MODES:
        for h in [40,36]:
            r=primary.query("efficiency_mode == @mode and hours_cap == @h").iloc[0]
            gains=[100*((1+r.A_req_pct/100)**(1/t)-1) for t in [3,5,10]]
            rows.append(dict(mode=mode,hours_cap=h,A_req_pct=r.A_req_pct,
                             **{f"annual_gain_{t}yr_pct":v for t,v in zip([3,5,10],gains)}))
            table_rows.append([MODE_SHORT[mode],f"{h}h",fmt(r.A_req_pct,3)]+[fmt(v,3) for v in gains])
    pd.DataFrame(rows).to_csv(out/"tfp_horizons.csv",index=False,encoding="utf-8-sig")
    table(out,"tab_tfp_horizons.tex","tab:tfp_horizons","Anualização contábil da compensação de produtividade",
          ["Função","Teto",r"$A_{\rm req}$ (\%)","3 anos","5 anos","10 anos"],table_rows,
          r"Os ganhos anuais em \% são $g_T=100[(1+A_{\rm req})^{1/T}-1]$, com $A_{\rm req}$ em fração. Base: horas formais limitadas a 44h. "
          r"A anualização apenas expressa a mesma diferença de nível em outra escala; não é uma trajetória dinâmica estimada. "
          r"Na PWT 11.0 via FRED, o crescimento anualizado de produtividade do Brasil foi " + fmt(growth(1990,2023),2) +
          r"\% em 1990--2023. Entre janelas de dez anos inteiramente contidas em 1990--2019, a maior taxa foi " +
          fmt(best[2],2) + rf"\% em {best[0]}--{best[1]}. "
          r"A série serve como referência descritiva de escala e não valida o contrafactual.",
          aligns="llrrrr")
    from original_tfp_figure import draw_tfp_figure
    draw_tfp_figure(d,out,savefig)
    dump(out/"tfp_provenance.json",{"source_url":"https://fred.stlouisfed.org/series/RTFPNABRA632NRUG",
        "pwt_url":"https://www.rug.nl/ggdc/productivity/pwt/","verified_date":"2026-09-05",
        "release":"Penn World Table 11.0","FRED_updated":"2026-02-04","variable":"rtfpna",
        "unit":"index 2021=1; annual; constant national prices","local_raw_sha256":sha(path),
        "best_10yr_window_restricted_to_1990_2019":{"start":best[0],"end":best[1],"growth_pct_year":best[2]},
        "reference_only_not_causal_validation":True})
    return hist,rows

def make_restored_experiments(run, national, out):
    from original_transition_figure import compute_transition_map, plot_transition_map
    from original_appendix_figures import compute_welfare_threshold, plot_welfare_threshold
    inputs=read(run/PRIMARY_FOLDER/"INPUTS.json")
    bridges=read(run/PRIMARY_FOLDER/"BRIDGE.json")
    transition,transition_checks=compute_transition_map(
        dict(inputs,bridges=bridges),REPLICATION,anchor_rows=national)
    transition.to_csv(out/"transition_map.csv",index=False,encoding="utf-8-sig")
    dump(out/"transition_map_checks.json",transition_checks)
    savefig(plot_transition_map(transition,transition_checks),out,"fig_transition_map_pt")
    welfare,welfare_checks=compute_welfare_threshold(
        inputs,bridges,replication_root=REPLICATION,anchor_rows=national)
    welfare.to_csv(out/"welfare_threshold.csv",index=False,encoding="utf-8-sig")
    dump(out/"welfare_threshold_checks.json",welfare_checks)
    savefig(plot_welfare_threshold(welfare,welfare_checks),out,"slide10c_welfare_threshold")
    return {"transition":transition_checks,"welfare_threshold":welfare_checks}


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir",type=Path,default=REPLICATION/"output/runs"/RUN_ID)
    parser.add_argument("--output-dir",type=Path,default=PAPER/"generated")
    args=parser.parse_args()
    run=args.run_dir.resolve();out=args.output_dir.resolve()
    out.mkdir(parents=True,exist_ok=True)
    checked=check_run(run)
    plt.rcParams.update({"font.family":"Times New Roman","font.size":10,"axes.titlesize":10.5,
                        "axes.labelsize":9.7,"xtick.labelsize":9,"ytick.labelsize":9,
                        "pdf.fonttype":42,"ps.fonttype":42})
    national=read(run/"COMPARATIVO_RESULTADOS.csv","csv")
    sectors_integral=read(run/"RESULTADOS_SETORIAIS.csv","csv")
    sensitivity_integral=read(run/"sensitivity/EMPIRICAL_SENSITIVITY.csv","csv")
    sectors_integral.loc[sectors_integral.scenario_variant.eq('empirical_bridge')].to_csv(
        out/'sectoral_results_integral.csv',index=False,encoding='utf-8-sig')
    sensitivity_integral.to_csv(out/'sensitivity_empirical_integral.csv',index=False,encoding='utf-8-sig')
    from baseline44_experiments import compute_baseline44_experiments, save_results
    extra=compute_baseline44_experiments(REPLICATION,run_dir=run)
    save_results(extra,out/'base44')
    for relative,expected in extra['source_hashes'].items():
        source=REPLICATION/relative
        if sha(source)!=expected:
            raise ValueError(f'Base44 source changed: {relative}')
        SOURCES[source.relative_to(PAPER.parent).as_posix()]=expected
    sectors=extra['sectoral']
    sensitivity=extra['sensitivity']
    primary=make_national_tables(national,out)
    df,anchor_error=curves(run,out,national)
    make_curve_figures(df,out)
    make_sensitivity(national,sensitivity,out)
    make_sectoral(sectors,out)
    details=read(run/PRIMARY_FOLDER/"RESULTS_FULL.json")
    make_decomposition(primary,out,details)
    hist,horizons=make_tfp(primary,out)
    restored_checks=make_restored_experiments(run,national,out)
    dump(out/"ASSET_MANIFEST.json",{"generated_utc":datetime.now(timezone.utc).isoformat(),
        "command":sys.argv,"python":sys.version,"platform":platform.platform(),
        "numpy":np.__version__,"pandas":pd.__version__,"matplotlib":matplotlib.__version__,
        "replication_run":run.name,"checked_archived_output_hashes":checked,
        "sources_sha256":SOURCES,"generator_sha256":sha(__file__),
        "figure_module_hashes":{p.name:sha(p) for p in sorted((PAPER/"scripts").glob("original_*_figure*.py"))},
        "all_module_hashes":{p.name:sha(p) for p in sorted((PAPER/"scripts").glob("*.py"))},
        "primary_reference":{"version":PRIMARY_VERSION,"folder":PRIMARY_FOLDER,
                             "hours_mapping":PRIMARY_MAPPING,"H0":PRIMARY_H0,
                             "assumption":"formal baseline min(observed,44), not observed contracted hours"},
        "base44_experiment_checks":extra['checks'],
        "restored_experiment_checks":restored_checks,
        "curve_rows":len(df),"canonical_anchor_max_error":anchor_error,
        "curve_restoration_max_error":float(df.restoration_residual.abs().max()),
        "interpretation":{"primary":"formal habitual hours explicitly capped44 in baseline, with recalibrated hourly bridge",
                          "alternative":"full observed habitual distribution retained as an explicit sensitivity",
                          "counterfactual":"habitual-hours cap proxy, not observed contracted hours",
                          "welfare":"representative mean; no worker-type incidence",
                          "sensitivity":"conditional grid, not identified set"},
        "outputs_sha256":{p.relative_to(out).as_posix():sha(p) for p in sorted(out.rglob('*')) if p.is_file() and p.name!="ASSET_MANIFEST.json"}})
    print(f"Assets rebuilt from {run.name}: {len(df)} curve points; maximum anchor difference {anchor_error:.3g}.")
    print(f"Historical rates: {hist}")
    print(f"5-year annualized compensation: {[(r['mode'],r['hours_cap'],r['annual_gain_5yr_pct']) for r in horizons]}")

if __name__=="__main__":main()
